# Generated by Django 4.2.14 on 2024-11-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_info_info_url_alter_info_info_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='info_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
