# Generated by Django 4.2.14 on 2024-11-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_alter_info_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='info_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
