# Generated by Django 4.2.14 on 2024-11-14 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_about_approach_session_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='info_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='info_url',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='info_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='info_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='info_video',
            new_name='video',
        ),
    ]
