# Generated by Django 4.2.14 on 2024-11-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_rename_info_image_info_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
